---
title: "leaflet_practice"
author: "Luke Vawter"
date: "October 18, 2018"
output: html_document
---
"Leaflet for R" is a helpful guide when working with leaflet:
https://rstudio.github.io/leaflet/json.html


a place to practice leaflet maps

```{r}
library(shiny)
library(leaflet)
library(dplyr)

df = read.csv("./cedr_phyto_station.csv", stringsAsFactors = F)

df$latitude <- as.numeric(df$latitude)
df$longitude <- as.numeric(df$longitude)

ui <- fluidPage(
    leafletOutput("mymap", height = 1000)
)

server <- function(input, output, session){
  
data <- reactive({
  x <- df
})
  
output$mymap <- renderLeaflet({
  m<-leaflet(data=df) %>%
    addTiles() %>%
    #setView(lng=73.935242, lat = 40.730610, zoom=10)
    addMarkers(lng= ~ longitude,
               lat= ~ latitude,
               popup = paste("Station", df$station, "<br>",
                             "Year:", df$stationdescription))
  m
})
}

shinyApp(ui = ui, server = server)
```

from a youtube tutorial
https://www.youtube.com/watch?v=07UB1lfHV-o :
```{r}
library(leaflet)
library(rgdal)

project.dir <- rprojroot::find_rstudio_root_file()

download.file("http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip",destfile = "TM_WORLD_BORDERS_SIMPL-0.3")

unzip("TM_WORLD_BORDERS_SIMPL-0.3.zip")

my_map = readOGR(dsn=getwd(), layer = "TM_WORLD_BORDERS_SIMPL-0.3")
# head(my_map)
# summary(my_map)
# 
# head(my_map$data)

leaflet(data = my_map) %>%
  addTiles() %>%
  setView(lat = 10, lng = 0, zoom = 2) %>%
  addPolygons(fillColor = "teal",
              highlight= highlightOptions(weight = 5,
                                          color="red",
                                          fillOpacity = .7,
                                          bringToFront = TRUE),
              label=my_map$NAME)

```

```{r}
library(shiny)
library(leaflet)
library(dplyr)
library(choroplethr)
library(choroplethrMaps)
library(rgdal)

project.dir <- rprojroot::find_rstudio_root_file()

# east.border <- readxl::read_excel(file.path(project.dir, "2018DREX_notes\data\Drought_Regions\eastern-region-border.shp"))


#file.path(project.dir, "2018DREX_notes\data\Drought_Regions")

map_path <- file.path(project.dir, "2018DREX_notes\\data\\Drought_Regions")

if( .Platform$OS.type == "unix" ) {map_path <- file.path(project.dir, "2018DREX_notes/data/Drought_Regions")}

eastern_region = readOGR(dsn=map_path, layer = "eastern-region")
#head(eastern_region)
summary(eastern_region)
head(eastern_region$COUNTY)

#ereg <- spTransform(eastern_region, CRS("+init=epsg:4326"))

# county <- subset(eastern_region, COUNTY %in% c(
#   "CAROLINE","DORCHESTER","KENT","QUEEN ANNES","SOMERSET","TALBOT"
# ))

# leaflet(eastern_region) %>%
#   addTiles() %>%
#   setView(lng=-77.01293195597827, lat=38.987549813483675, zoom = 6) %>%
#   addPolygons(fillColor = "red",
#               highlight= highlightOptions(weight = 5,
#                                           color="blue",
#                                           fillOpacity = .7,
#                                           bringToFront = TRUE)#,
#               #label=eastern_region$COUNTY
# )



# leaflet(neStates) %>%
#   addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
#     opacity = 1.0, fillOpacity = 0.5,
#     fillColor = ~colorQuantile("YlOrRd", ALAND)(ALAND),
#     highlightOptions = highlightOptions(color = "white", weight = 2,
#       bringToFront = TRUE))

```

https://rstudio.github.io/leaflet/shapes.html
currently broken... to be continued:
```{r}
library(rgdal)

project.dir <- rprojroot::find_rstudio_root_file()

download.file("https://www.census.gov/geo/maps-data/data/cbf/cbf_state.html",destfile = "shp/cb_2013_us_state_20m.shp")

#unzip("cb_2017_us_state_500k.zip")

# From https://www.census.gov/geo/maps-data/data/cbf/cbf_state.html
states <- readOGR(dsn=getwd(), "shp/cb_2013_us_state_20m.shp",
  layer = "cb_2013_us_state_20m", GDAL1_integer64_policy = TRUE)

neStates <- subset(states, states$STUSPS %in% c(
  "CT","ME","MA","NH","RI","VT","NY","NJ","PA"
))

leaflet(neStates) %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~colorQuantile("YlOrRd", ALAND)(ALAND),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE))
```



working template, rough non-functional scratch paper at the moment:
```{r}
library(shiny)
library(leaflet)
library(dplyr)
library(choroplethr)
library(choroplethrMaps)

project.dir <- rprojroot::find_rstudio_root_file()

# east.border <- readxl::read_excel(file.path(project.dir, "2018DREX_notes\\data\\Drought_Regions\\eastern-region-border.shp"))





erb = readOGR(file.path(project.dir, "2018DREX_notes\\data\\Drought_Regions\\eastern-region-border.shp"), layer = "eastern-region-border")



ui <- fluidPage(
    leafletOutput("mymap", height = 1000)
)

server <- function(input, output, session){
  
data <- reactive({
  x <- df
})
  
output$mymap <- renderLeaflet({
  m<-leaflet(data=df) %>%
    addTiles() %>%
    #setView(lng=73.935242, lat = 40.730610, zoom=10)
    addMarkers(lng= ~ longitude,
               lat= ~ latitude,
               popup = paste("Station", df$station, "<br>",
                             "Year:", df$stationdescription))
  m
})
}

```

using https://hautahi.com/rmaps to learn how to take a closer look at a shapefiles content.

inspection of all region shapefiles:
```{r}
library(shiny)
library(leaflet)
library(dplyr)
library(choroplethr)
library(choroplethrMaps)
library(rgdal)

project.dir <- rprojroot::find_rstudio_root_file()



map_path <- file.path(project.dir, "2018DREX_notes\\data\\Drought_Regions")

if( .Platform$OS.type == "unix" ) {map_path <- file.path(project.dir, "2018DREX_notes/data/Drought_Regions")}

eastern_region = readOGR(dsn=map_path, layer = "eastern-region")

eastern_region_border = readOGR(dsn=map_path, layer = "eastern-region-border")

clipsouthern3 = readOGR(dsn=map_path, layer = "clipsouthern3")

wssc_service = readOGR(dsn=map_path, layer = "wssc service")

clipcentral = readOGR(dsn=map_path, layer = "clipcentral")

baltimore_service = readOGR(dsn=map_path, layer = "baltimore service")


clipcentral_border = readOGR(dsn=map_path, layer = "clipcentral-border")

clipsouthern_border = readOGR(dsn=map_path, layer = "clipsouthern-border")

#eastern_region %>%
  #select(COUNTY) %>%
  #print()
  
eastern_region %>%
  #shows the bounding box which is the smallest rectangle that will hold all of the points
  bbox() #%>%

#this code prints the data( in dataframe) of the shapefile
head(eastern_region@data)
  
#this prints values in COUNTY column in data
print(eastern_region@data$COUNTY)

#This plots the region polygon
plot(eastern_region); title(main = list("Maryland eastern region "), cex=0.8)

plot(eastern_region_border); title(main = list("Maryland eastern region border"), cex=0.8)

plot(clipsouthern3); title(main = list("Maryland clipsouthern3"), cex=0.8)


plot(wssc_service); title(main = list("Maryland wssc service"), cex=0.8)

plot(clipcentral); title(main = list("Maryland clipcentral"), cex=0.8)

plot(baltimore_service); title(main = list("Maryland baltimore service"), cex=0.8)

plot(clipcentral_border); title(main = list("Maryland clipcentral"), cex=0.8)

plot(clipsouthern_border); title(main = list("Maryland clipsouthern-border"), cex=0.8)


```

