---
title: "R practice"
author: "Luke Vawter"
date: "September 18, 2018"
output: html_document
---

factors in R:
https://swcarpentry.github.io/r-novice-inflammation/12-supp-factors/
not char or string,
they are integers and behave as such
```{r}


fruits <- factor(c("grape", "bananna", "grape", "bananna", "apple", "orange"))
#sets order of factor levels
fruits <- factor(fruits, levels = c("orange", "grape", "bananna", "apple"), ordered = TRUE)
levels(fruits)
nlevels(fruits)

fruits %>%
  trimws() %>%
  print()

```

trimws():
```{r}
thing <- " this is a test   "
print(trimws(thing))
#and again using pipes
thing %>% 
  trimws() %>%
  print()

```
playing with select, filter,     :
```{r}


toy.df <- read_excel(file.path(project.dir, "data/jackie_data/Data 2013_4plus-phyto-metrics.xlsx"),
                         sheet = "DATA_4+biometrics",
                         skip = 1)

#colnames(toy.df)

new.toy.df <- toy.df %>%
  #include only those columns starting with s
  select(starts_with("s")) %>%
  
  #only include rows which fall within given ranges
  filter(SURVEY_ID <= 30867, SALINITY < 6) %>%
  #select(SURVEY_ID:SAMPLE_DATE) %>
  
  #arrange in descending order based on SURVEY_ID value
  arrange(desc(SURVEY_ID)) %>%
  print()

mutant.toy.df <- toy.df %>%
  
  mutate(nonsense=SECCHI/SALINITY) %>%
  print()
  
#also could do group_by()
```

```{r}


toy.df <- read_excel(file.path(project.dir, "data/jackie_data/Data 2013_4plus-phyto-metrics.xlsx"),
                         sheet = "DATA_4+biometrics",
                         skip = 1)

map(SEASON, print("count") )


```

