---
title: "Shiny_practice"
author: "Luke Vawter"
date: "September 12, 2018"
output: html_document
---

a space for practicing basic shiny app elements, features and ...well.. practices:

isolate(input$value...) makes input non-reactive

observeEvent

test of Render UI
use explained in tutorial https://www.youtube.com/watch?v=JUop-YfRAuw:
```{r}
library(shiny)
library(dplyr)
#value <- "color:black"
ui <- fluidPage(
  title = "test",
  selectInput(inputId = "thing", label = "choose a fruit", choices = c("apples", "oranges", "banannas") ),
  htmlOutput("first")
  
)

server <- function(input, output)({
 
  value <- eventReactive(input$thing, { case_when(
    input$thing == "apples" ~ "color: red",
    input$thing == "oranges" ~ "color: orange",
    input$thing == "banannas" ~ "color: yellow"
    
  )
  })
  #output$first <- renderText({value()})
  output$first <- renderUI({
    withTags(
      div(style= value(),
          p("words")))

  })
  
})




shinyApp(ui, server)
```

pulled from stack-overflow:
```{r}
library(shiny)

ui <- fluidPage(
  selectInput("num", "Choose a number", 1:10),
  conditionalPanel(
    condition = "output.square",
    "That's a perfect square!"
  )
)

server <- function(input, output, session) {
  output$square <- reactive({
    sqrt(as.numeric(input$num)) %% 1 == 0
  })
  outputOptions(output, 'square', suspendWhenHidden = FALSE)
}

shinyApp(ui = ui, server = server)

```

```{r}
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "break me"
                  ),
  dashboardSidebar(dateInput("date", "enter a date")
                   ),
  dashboardBody(htmlOutput(outputId = "boxes")
  )
)
  
server <- function(input, output, session) {
 
output$boxes  <- renderUI({
  div(class="topbox_main",
    div(class="topbox1",
        div(class="square",style="precip_value",#"background-color:yellow"
            div(class="content",
                div(class="table",
                    div(class="table-cell",
                        p("precipitation deficit")
                    )))), 
        div(class="square", style="background-color:red",
            div(class="content",
                div(class="table",
                    div(class="table-cell",
                        p("ground water wells")
                    )))),
        div(class="square", style="background-color:green",
            div(class="content",
                div(class="table",
                    div(class="table-cell",
                        p("reservoir flow")
                    )))),
        div(class="square", style="background-color:orange",
            div(class="content",
                div(class="table",
                    div(class="table-cell",
                        p("streamflow")
                    ))))
    ), #end of topbox1
    div(class="topbox2", 
        div(class="square", style="background-color:yellow",
            div(class="content",
                div(class="table",
                    div(class="table-cell",
                        p("precipitation deficit")
                    )))),
        div(class="square", style="background-color:orange",
            div(class="content",
                div(class="table",
                    div(class="table-cell",
                        p("ground water wells")
                    )))),
        div(class="square", style="background-color:red",
            div(class="content",
                div(class="table",
                    div(class="table-cell",
                        p("reservoir flow")
                    )))),
        div(class="square", style="background-color:green",
            div(class="content",
                div(class="table",
                    div(class="table-cell",
                        p("streamflow")
                    ))))
    ) #end of topbox2
  ) #end of topbox-main
})
}


shinyApp(ui = ui, server = server)

```

```{r}
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "break me"
                  ),
  dashboardSidebar(dateInput(inputId = "date", "enter a date")
                   ),
  dashboardBody(htmlOutput(outputId = "boxes")
  )
)
  
server <- function(input, output, session) {

path_p <- "C:\\Users\\icprbadmin\\Documents\\R\\2018drex\\input\\ts\\state\\i_a1b\\va_shenandoah_p.csv"
my_data_p = read.csv(path_p)  

p_data_percent <- eventReactive(input$date, {
  input$date
  # for(i in my_data_p$date){
  # 
  #   case_when(
  #   as.character(i) == date_func(as.character(input$date))~ my_data_p$p_percent_normal[which(my_data_p$date == i)])
  
  #}
  
#my_data_p$p_percent_normal[input$data_index]
})
  
output$boxes  <- renderUI({
div(as.character(p_data_percent()))
})
}


shinyApp(ui = ui, server = server)

```

```{r}
library(shiny)
library(shinydashboard)

ui <- fluidPage(
  dateRangeInput("plot_range",
               "Specify plot range",
#               start = "1929-10-01",
#               end = "1930-12-31",
               start = "1998-10-10",
               end = "1999-10-10",
               format = "yyyy-mm-dd",
               width = NULL),
  htmlOutput(outputId = "boxes")
)

server <- function(input, output, session) {
output$boxes  <- renderUI({
div(paste0(" index1: ",input$plot_range[1]," index 2: ",input$plot_range[2]))
})
}

shinyApp(ui = ui, server = server)

```

```{r}
library(shiny)
library(shinydashboard)
library(dplyr)

ui <- fluidPage(dateInput(inputId = "date", label = "enter a date", value = "1998-10-04"),htmlOutput(outputId = "boxes")
                )

server<-function(input, output, session){
                path_p <- "C:\\Users\\icprbadmin\\Documents\\R\\2018drex\\input\\ts\\state\\i_a1b\\va_shenandoah_p.csv"
                path_q <- "C:\\Users\\icprbadmin\\Documents\\R\\2018drex\\input\\ts\\state\\i_a1b\\va_shenandoah_q.csv"
                #path_s <- "C:\\Users\\icprbadmin\\Documents\\R\\2018drex\\input\\ts\\state\\i_a1b\\va_shenandoah_stor.csv"
                #path_g <- "C:\\Users\\icprbadmin\\Documents\\R\\2018drex\\input\\ts\\state\\i_a1b\\va_shenandoah_gw.csv"

                #for mac use
                if( .Platform$OS.type == "unix" ) {
                  path_p <- "/Users/lukevawter/Desktop/R/2018drex/input/ts/state/i_a1b/va_shenandoah_p.csv"
                  path_q <- "/Users/lukevawter/Desktop/R/2018drex/input/ts/state/i_a1b/va_shenandoah_q.csv"
                  #path_s <- "/Users/lukevawter/Desktop/R/2018drex/input/ts/state/i_a1b/va_shenandoah_stor.csv"
                  #path_g <- "/Users/lukevawter/Desktop/R/2018drex/input/ts/state/i_a1b/va_shenandoah_gw.csv"
                }

                my_data_p = read.csv(path_p)
                my_data_q = read.csv(path_q)
                #my_data_s = read.csv(path_s)
                #my_data_g = read.csv(path_g)
                
                find_date <- function(col_date, col_val ){
                  col_val <- 0
                  for(i in col_date){
                    if(as.character(i) == "1998-10-06"){our_value <- (col_val[which(col_date == i)])}
                }
                  return(our_value)}
                
                p_data_percent<-eventReactive(test_date$test_date_value, {#"hi"
                  find_date(my_data_p$date, my_data_p$p_percent_normal)
                  #for(i in my_data_p$date){

                    #case_when(1==1)~("Hi")
                    # as.character(i) == as.character(test_date$test_date_value)~ my_data_p$p_percent_normal[which(my_data_p$date == i)])

                  #}
                  
                #my_data_p$p_percent_normal[input$data_index]
                })
                # q_data_percent <- eventReactive(input$data_index, {
                #   my_data_q$flow_cfs[input$data_index]
                # })   
           
                output$boxes  <- renderUI({
                div(as.character(p_data_percent()))
                })
           
                observeEvent(input$date, {
                  test_date$test_date_value <- input$date
                })
                
                test_date <- reactiveValues(test_date_value = "1930-05-01")
                
               
}

shinyApp(ui = ui, server = server)
```

```{r}
library(readxl)
library(dplyr)
library(shiny)
library(shinydashboard)

ui <- fluidPage(dateInput(inputId = "date", label = "enter a date", value = "1998-10-04"),htmlOutput(outputId = "boxes")
                )


server<-function(input, output, session){

output$date_text  <- renderText({paste("Today's date is",   as.character(test_date$test_date_value))
              })
  
output$boxes  <-renderUI({div(as.character(p_data_percent()))
                })

date_func <- function(col_date, col_val, date_today ){
  our_value <- 0
  for(i in col_date){
    if(as.character(i) == date_today){our_value <- (col_val[which(col_date == i)])}
  }
  return(our_value)}


my_data_p <-data.table::fread(paste("handmade_test_data.csv", sep = ""))#"test_data.csv", sep = ""))
  # my_data_p <- my_data_p %>% 
  # mutate(date = as.Date(date))

p_data_percent <- eventReactive(test_date$test_date_value, {
    date_func(my_data_p$date, my_data_p$p_percent_normal, test_date$test_date_value)

  })
                
  test_date <- reactiveValues(test_date_value = "1930-05-01")
                

}


shinyApp(ui = ui, server = server)
```


https://shiny.rstudio.com/gallery/plot-interaction-zoom.html:
```{r}
library(shiny)
library(ggplot2)

ui <- fluidPage(
  tags$script(HTML(
    "document.body.style.backgroundColor = 'skyblue';"
  )),
    fluidRow(
    column(width = 4, class = "well",
      h4("Brush and double-click to zoom"),
      plotOutput("plot1", height = 300,
        dblclick = "plot1_dblclick",
        brush = brushOpts(
          id = "plot1_brush",
          resetOnNew = TRUE
        )
      )
    )
)
)

server <- function(input, output, session){
  
  ranges <- reactiveValues(x = NULL, y = NULL)
  
  output$plot1 <- renderPlot({
    ggplot(data = mpg) +
      geom_point(mapping = aes(x = displ, y = hwy, color = class, shape = drv))+
      coord_cartesian(xlim = ranges$x, ylim = ranges$y, expand = FALSE)
})
  
  # When a double-click happens, check if there's a brush on the plot.
  # If so, zoom to the brush bounds; if not, reset the zoom.
  observeEvent(input$plot1_dblclick, {
    brush <- input$plot1_brush
    if (!is.null(brush)) {
      ranges$x <- c(brush$xmin, brush$xmax)
      ranges$y <- c(brush$ymin, brush$ymax)

    } else {
      ranges$x <- NULL
      ranges$y <- NULL
    }
  })
  
}

shinyApp(ui = ui, server = server)
```

```{r}
my_path =  file.path('C:\\Users\\icprbadmin\\Documents\\R_Scripts\\workflow\\data\\DREX\\images\\test_bulb.png')
    
library(png)

ui <- fluidPage(
  #imageOutput("my_image")
  plotOutput("my_image")
)

server <- function(input, output,session)({
  output$myImage <- renderPlot({#Image({

    readPNG(my_path, TRUE, FALSE)
    #test <- writePNG(img)
    

  })
})

shinyApp(ui = ui, server = server)
```
```{r}
shinyUI(pageWithSidebar(
  headerPanel("renderImage example"),
  sidebarPanel(
    sliderInput("obs", "Number of observations:", 
                min = 0, max = 1000,  value = 500)
  ),
  mainPanel(
    imageOutput("myImage")
  )
))


shinyServer(function(input, output, clientData) {
  output$myImage <- renderImage({
    # A temp file to save the output.
    # This file will be removed later by renderImage
    outfile <- tempfile(fileext='.png')

    # Generate the PNG
    png(outfile, width=400, height=300)
    hist(rnorm(input$obs), main="Generated in renderImage()")
    dev.off()

    # Return a list containing the filename
    list(src = outfile,
         contentType = 'image/png',
         width = 400,
         height = 300,
         alt = "This is alternate text")
  }, deleteFile = TRUE)
})
```

```{r}
library(shiny)
ui <- fluidPage(



# App title ----
  titlePanel("Downloading Data"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Choose dataset ----
      selectInput("dataset", "Choose a dataset:",
                  choices = c("rock", "pressure", "cars")),

      # Button
      downloadButton("downloadData", "Download")

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      tableOutput("table")

    )

  )
)
#server.r
server <- function(input, output) {

  # Reactive value for selected dataset ----
  datasetInput <- reactive({
    switch(input$dataset,
           "rock" = rock,
           "pressure" = pressure,
           "cars" = cars)
  })

  # Table of selected dataset ----
  output$table <- renderTable({
    datasetInput()
  })

  # Downloadable csv of selected dataset ----
  output$downloadData <- downloadHandler(
    filename = function() {
      paste(input$dataset, ".csv", sep = "")
    },
    content = function(file) {
      shiny::withProgress(
        message = paste0("Downloading", input$dataset, " Data"),
        value = 0,
        {
          shiny::incProgress(1/10)
          Sys.sleep(1)
          shiny::incProgress(5/10)
          write.csv(datasetInput(), file, row.names = FALSE)
        }
      )
    }
  )

}
shiny::shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)
ui <- fluidPage(
  
  # # App title ----
  # titlePanel("Downloading Data"),
  # 
  
  tabPanel("Download Data",
         fluidRow( # major row that contains whole body
           column( # major column that contains whole body
             width = 12,
             
             column(  # this is the 1st main column - with the buttons
               width = 6,
               
               actionButton("download_data_w",
                            "Download data",
                            icon = NULL,
                            width = "220px"),
               actionButton("view_data_w",
                            "Observe the data",
                            icon = NULL,
                            width = "220px"),
               actionButton("accept_data_w",
                            "Accept and save the data",
                            icon = NULL,
                            width = "220px"),
             ) #this is the end of the 1st main column
           )
         )
  )
  )

server <- function(input, output) {

    withProgress(message = "downloading data", value = 0, {
      incProgress(1/2)
  demands_raw.df <- data.table::fread("http://icprbcoop.org/drupal4/products/coop_pot_withdrawals.csv",
                                      header = TRUE, data.table = FALSE) #, colClasses = list_gage_locations)
  
  incProgress(1/2)
})
  
  
}
  
shiny::shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)
my_NA_count = 0

ui <- fluidPage( 
 sidebarPanel(
   print(my_NA_count),

   conditionalPanel(
      condition = "my_NA_count >  1'",
      sliderInput("breakCount", "pass", min=1, max=1000, value=10)
      #print("pass")
      ),


      # Only show this panel if na count is one or higher
      conditionalPanel(
         condition = "my_NA_count <= 1'",
         sliderInput("breakCount", "fail", min=1, max=1000, value=10)
         #print("fail")

      )
   
)
   )

server <- function(input, output) {
  
}
  
shiny::shinyApp(ui = ui, server = server)
```

```{r}
library(shiny)

ui <- fluidPage(
  actionButton("pass_fail","select"),
  selectInput("pass_fail_input", "select pass or fail", c("PASS" = "pass", "FAIL" = "fail")),#,
  
  conditionalPanel("input.pass_fail_input == 'pass'",       sliderInput("breakCount", "pass", min=1, max=1000, value=10)
  ),
  
    conditionalPanel("input.pass_fail_input == 'fail'",       sliderInput("breakCount", "fail", min=1, max=1000, value=10)
  )
)

server <- function(input, output, session) {

}

shinyApp(ui, server)
```

```{r}
library(shiny)
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(lubridate)

data_path <- "data/CEDR/"

#---------------------check data-------------------------------
check_data <-  function(){
    withProgress(message = "downloading water quality data", value = 0, {
          incProgress(1/2)
  data_tweak.df <- data.table::fread(paste0(data_path, "cedr_wq_tweak.csv"),
                                   data.table = FALSE)
    data_na_count <- as.numeric(sum(is.na(data_tweak.df$measurevalue)))
    incProgress(1/2)


  data_num <- nrow(data_tweak.df)


  data_na_percent <- (data_na_count / data_num)

  data_check <- case_when( data_na_percent >=  .05 ~ paste("FAIL ","NA percent: ",data_na_percent), data_na_percent <  .05 ~ paste("PASS ","NA percent: ",data_na_percent)) #TRUE ~ "PASS")
  return(data_check)
  }) #end of withProgress
}
#------------------------end check data-----------------------

#------------------------ui----------------------------------
ui <- fluidPage(

  actionButton("download_data",
               "Download data",
               icon = NULL,
               width = "220px"
               ),
  verbatimTextOutput("pass_fail")

) #end of fluidpage
#--------------------------end ui----------------------------


#-------------------------server------------------------------
server <- function(input, output, session) {
   output$pass_fail <-  eventReactive(input$download_data, {
    check_data() 
    
  })
   

 
}
#------------------------end server-----------------------------


shinyApp(ui, server)
```


rednering tables in shiny
```{r}


#------------------------ui----------------------------------
ui <- fluidPage(


  DT::dataTableOutput("mytable")

) #end of fluidpage
#--------------------------end ui----------------------------


#-------------------------server------------------------------
server <- function(input, output, session) {

 output$mytable <- DT::renderDataTable({     data_modified.df <- data.table::fread(paste0(data_path, "data_modified.csv"),
                                        data.table = FALSE) %>%
   
      #filter(problem == "qq")
    
    
    mutate(error_code = problem) %>%
    mutate(definition = case_when(problem == "a"~A,
                                  problem == "b"~B,
                                  problem == "bb"~BB,
                                  problem == "c"~C,
                                  problem == "d"~D,
                                  problem == "dd"~DD,
                                  problem == "e"~E,
                                  problem == "ff"~FF,
                                  problem == "gg"~GG,
                                  problem == "i"~I,
                                  problem == "j"~J,
                                  problem == "jj"~JJ,
                                  problem == "lb"~LB,
                                  problem == "ls"~LS,
                                  problem == "lu"~LU,
                                  problem == "mm"~MM,
                                  problem == "nn"~NN,
                                  problem == "p"~P,
                                  problem == "qq"~QQ,
                                  problem == "r"~R,
                                  problem == "rr"~RR,
                                  problem == "ss"~SS,
                                  problem == "u"~U,
                                  problem == "v"~V,
                                  problem == "vv"~VV,
                                  problem == "ww"~WW,
                                  problem == "x"~X,
                                  TRUE~"no problem") ) %>%
    filter(definition != "no problem") %>%
    group_by(error_code) %>%
    mutate(n = n()) %>%
   ungroup() %>%
    select(error_code,definition, n) %>%
   unique()
  
  


   
 })#end of output$mytable

 
}
#------------------------end server-----------------------------


shinyApp(ui, server)
```

and this is a version using reactiveValues()
```{r}


#------------------------ui----------------------------------
ui <- fluidPage(


  DT::dataTableOutput("mytable")

) #end of fluidpage
#--------------------------end ui----------------------------


#-------------------------server------------------------------
server <- function(input, output, session) {
  
  test_reactive_value <-  reactiveValues()
  test_reactive_value$data <- NULL

 output$mytable <- DT::renderDataTable({     test_reactive_value$data <- data.table::fread(paste0(data_path, "data_modified.csv"),
                                        data.table = FALSE) %>%
   
      #filter(problem == "qq")
    
    
    mutate(error_code = problem) %>%
    mutate(definition = case_when(problem == "a"~A,
                                  problem == "b"~B,
                                  problem == "bb"~BB,
                                  problem == "c"~C,
                                  problem == "d"~D,
                                  problem == "dd"~DD,
                                  problem == "e"~E,
                                  problem == "ff"~FF,
                                  problem == "gg"~GG,
                                  problem == "i"~I,
                                  problem == "j"~J,
                                  problem == "jj"~JJ,
                                  problem == "lb"~LB,
                                  problem == "ls"~LS,
                                  problem == "lu"~LU,
                                  problem == "mm"~MM,
                                  problem == "nn"~NN,
                                  problem == "p"~P,
                                  problem == "qq"~QQ,
                                  problem == "r"~R,
                                  problem == "rr"~RR,
                                  problem == "ss"~SS,
                                  problem == "u"~U,
                                  problem == "v"~V,
                                  problem == "vv"~VV,
                                  problem == "ww"~WW,
                                  problem == "x"~X,
                                  TRUE~"no problem") ) %>%
    filter(definition != "no problem") %>%
    group_by(error_code) %>%
    mutate(n = n()) %>%
   ungroup() %>%
    select(error_code,definition, n) %>%
   unique()
  
  


   
 })#end of output$mytable

 
}
#------------------------end server-----------------------------


shinyApp(ui, server)


```

