---
title: "DREX_colors"
author: "Luke Vawter"
date: "August 29, 2018"
output: html_document
---

Working on 2018 DREX color quad display for Shenandoah and Northern Virginia.  Quads are:
precipitation, ground water wells, stream flow, reservoir flows.

Cherie will provide data for you to play with in 2018DREX/inputs repo.  

The code will consist of some basic control flow in R.
A basic example follows:

```{r}
my_vec -> c(1,2,3,4,5,6,7,8,9,10,11,12)
for (i in my_vec) {
  if (i >= 0 && i < 3){
    color = "#e5e102"
    print(color)
  }
  else if (i >= 3 && i < 5){
    color = "#e5b702"
    print(color)
  }
  else if (i >= 5 && i < 7){
   color = "#e59502"
   print(color)
  }
  else if (i >= 7 && i < 9){
   color = "#e57702"
   print(color)
  }
  else if (i >= 9 && i < 11){
   color = "#e55102"
   print(color)
  }
  else if (i >= 11 && i <13){
    color = "#e52402"
    print(color)
  }
  else{
    color = "#000000"
    print(color)
  }
}





```

Toy code using provided data:

```{r}
print("this is a place for the basic boolean logic")
```

