---
title: "DREX_notes"
author: "Luke Vawter"
date: "September 11, 2018"
output: html_document
---

A place for random thoughts and notes on DREX:


----------------------UI--------------------------
Done-
-build toy logic and Shiny app(DREX_toy_colors.Rmd)
-added external css to DREX
-branched that version of DREX
-write code to pull data from 2018DREX/inputs/state/...(csv) into dataframe
-adapt existing toy logic to data frame range
-learn that dashboard and shinydashboard are not the same thing. installed shinydashboard
-make a square with changable background color(valueBox)
-apply adapted logic to square in toy
-add date column value as subtitle in valueBoxOutput
-build quadrants as raw html in toy Shiny ui
-moderate testing of  extent of control added css has over DREX(Shiny Dashboard framework may limit control)
-add quadrants structure(multiple valueBox with css shrinking and arranging, or raw html elements?)
...went raw html but it needs major tweaking..good first steps
-tag$li for login bar access
-(optional)integrate toy into DREX alterante branch for testing purposes
-output sim_today varaible output reactively to tag$li in login bar
-build toy DREX for testing/practice of:
html/css feature integration, various reactive render types, andShiny in general
-add an inputSlider to toy for date selection
-write code to convert date format
-link existing code to current date rather than slider in shinytestapp2
-add otdays_date to login bar of 2018DREX  master branch
-learn where/how to plug in your code for squares
-add title bars above squares
-write code to iter thru df, find date and spit out value
-fix/finish integration of proto squares in DREX
-learn in office standard practice for csv to dataframe(look at DREX, use fread)
-move my paths from global to paths.R, in 2018drex/config
-put the dummy input time series for the state data in 2018drex/input/ts/1929_1929prrism for now 
-add second square to Virginia panel
-replace infoboxes with css/html
-add value input(or placeholder) for 'riverflow increase due to restriction'
-add placeholder MD drought map
-change presentatioon of squares to better mirror state warning standards(for Md and Va)
-deep testing of extent of control added css has over DREX
-change to P, GW, SW ,R and increase font size
-change to lighter green
-change "FLOW..." to header (display:block)
-fix FLOW positioning
-change text in colored box of custom infobox to black
-colored box in custom infobox made longer
-increase p3 custom class fon size
-increase size of titles (Maryland/VRGINIA DROUGHT STATUS) by changing them from titles to html p tags of custom class .title
-center P,GW,SW,R
-right-align num in Flow Bene. MGD(actually looks better centered)
-figure out how to plot drought status shapefiles
-optimize design of DREX ui if/where able(ongoing)
-map projection is "Maryland State Plane NAD-83" which looks to be ESPG:26985
-email John about missing western region in shapefile
-switch position of infox output and text
-make Shen and Nova font bigger
-link squares to toy code

Doing-
-better document your code within DREX 2018 or you will regret it
-change todays date from rendertext to renderUI and then adjust positioning



-link Flows number to toy code
-space quadrants out a bit

-put our app on shiny.io(publish)

-add state maps(choropleth map using leaflet?
https://rstudio.github.io/leaflet/choropleths.html)

-explore zoom tool for graphs
-change default value of our_value variable to NA and default color to grey to match drought watch standard display

-fix "character string is not in a standard unambiguous format" issue
-thorough bug testing of squares
-write bool logic to replace current pseudo logic for precip, gw, reservoir(q), and stor






UI adjustments needed (after meeting Wed 9/12/18):
DONE-tighten layout (adjust heighs)(icon size block further height adjustment)
DONE-remove "Flow at Point of Rocks Panel"
DONE-move quadrant of graphs up(Cherie did this)
-inscrease readabbility of large graph, simply small graphs
DONE-tweak css until it pops(sorta did this)



-----------------------Debugging--------------------------

Done-
-start generating and documenting instances of buggy behavior
-look at generated outputs from running sim and writing time series
-run DREX multiple times 
--create debug branch of DREX
-explore including a reactive relationship from days_added(sp?) to DREXtoday
-learn reactive values

Doing-

-read through all of DREX code at least once
-add date input validation method
-become familiar with output deviations between input types(last day select vs. add chunk of days)
-look at generated outputs from running sim
-start learning water process policy

-isolate and execute pieces of suspect code
-play with add days code in isolation of the rest of the codebase



Bugs:
-crashes on date inputs outside of expected range

Files read through:
-ui, sim_add_days_func, server, reservoir_ops_today, import_data, load_packages, global

Files to read through:
 global, simulation_func, forecasts_flows_func, rule_curve_func, sim_main_func, reservoir_opts_init_func, forecasts_demands_func, estimate_need_func, date_func, reservoir_class, reservoirs_make,
 potomac_flows_init, forecasts, demands_maybediscard,


note:input$run_main is a click of 're-run simulation' buttion

input files to be aware of:  flows_daily_mgd.csv and demands_daily.csv in input/ts/1929_1929prrism/ 

the output files created for QAing: 
output_flows.csv - the flows in the river
output_pat.csv - what happens in the Patuxent reservoir
the 3 functions that do the calculations:
simulation_func - which calls reservoir_ops_today_func and forecasts_flows_func
---------------------------------------------------------



server

  observeEvent(input$run_main, {
    test_date$test_date_value <- input$DREXtoday
    ts <- sim_main_func(input$DREXtoday, ts)
  })
  #
  # Allow the user to add chunks of days to the simulation
  observeEvent(input$run_add, {
    test_date$test_date_value <- as.Date(input$DREXtoday) +input$chunkofdays
    ts <- sim_add_days_func(input$chunkofdays, ts)
  })
  
  test_date <- reactiveValues(test_date_value = "1930-05-01")
  #
  
  
  
    #date to login bar
  output$date_text  <- renderText({
    paste("Today's date is", as.character(test_date$test_date_value))#input$DREXtoday))
  })
  